import { UsersService } from './users.service';
import { AuthService } from '../../auth/auth.service';
export declare class UsersController {
    private usersService;
    private authService;
    constructor(usersService: UsersService, authService: AuthService);
    get(type: string): Promise<any>;
    add(userDTO: any): Promise<any>;
    getUser(name: string): Promise<any>;
    updateUser(name: string, userDTO: any): Promise<any>;
    deleteUser(userName: string): Promise<any>;
    getUserRoles(userName: string): Promise<any>;
    updateUserRoles(userName: string, rolesDTO: any): Promise<any>;
    updatePrivileges(userName: string, privilegesDTO: any): Promise<any>;
    getPrivileges(userName: string): Promise<any>;
    updatePrivilegesSchedule(userName: string, privilegesScheduleDTO: any): Promise<any>;
    updateProfilePic(userName: string, profilePicDTO: any): Promise<any>;
    getProfilePic(userName: string): Promise<any>;
    updateHomeRoute(userName: string, homeRouteDTO: any): Promise<any>;
    getHomeRoute(userName: string): Promise<any>;
    updateProfile(userName: string, profileDto: any): Promise<any>;
    updateFullName(userName: string, fullName: any): Promise<any>;
    updateProfileName(userName: string, profileNameDTO: any): Promise<any>;
    updateAddress(userName: string, AddressDTO: any): Promise<any>;
    updatePhoneNumber(userName: string, phoneNumberDTO: any): Promise<any>;
    updateEmail(userName: string, alternetEmailDTO: any): Promise<any>;
    activate(userName: string): Promise<any>;
    dective(userName: string): Promise<any>;
    updateActivation(userName: string): Promise<any>;
    updateMaritalStatus(userName: string, user: any): Promise<any>;
    isActive(userName: string, user: any): Promise<any>;
    isLocked(userName: string, user: any): Promise<any>;
    lock(userName: string, user: any): Promise<any>;
    unlock(userName: string, user: any): Promise<any>;
    getAuthStatus(userName: string): Promise<any>;
    getAccessRoutes(userName: string): Promise<any>;
    isOnline(userName: string): Promise<any>;
    getActivities(userName: string): Promise<any>;
    addActivity(userName: string, activityDTO: any): Promise<any>;
    changePassword(userName: string, user: any): Promise<any>;
}
