import { Model } from 'mongoose';
import { AuthService } from 'src/auth/auth.service';
import { MenusService } from '../menus/menus.service';
export declare class UsersService {
    private users;
    private userActivities;
    private authService;
    private menusService;
    constructor(users: Model<any>, userActivities: Model<any>, authService: AuthService, menusService: MenusService);
    get(type?: any): Promise<any[]>;
    verifyName(email: any): Promise<boolean>;
    add(userDTO: any): Promise<unknown>;
    updateUserRoles(name: any, rolesDTO: any): Promise<any>;
    getUser(email: any): Promise<any>;
    updateUser(email: any, userDTO: any): Promise<any>;
    getUserRole(email: any): Promise<any>;
    getUserRoles(user: any): Promise<any>;
    updatePrivileges(userName: any, privilegesDTO: any): Promise<string>;
    getPrivileges(userName: any): Promise<string>;
    updatePrivilegesSchedule(userName: any, privilegesScheduleDTO: any): Promise<string>;
    updateHomeRoute(name: any, homeRouteDTO: any): Promise<any>;
    getHomeRoute(email: any): Promise<any>;
    updateProfilePic(userName: any, profilePicDTO: any): Promise<string>;
    getProfilePic(userName: any): Promise<string>;
    updateProfile(userName: any, profileDTO: any): Promise<string>;
    updateFullName(userName: any, fullNameDTO: any): Promise<string>;
    updateProfileName(userName: any, profileNameDTO: any): Promise<string>;
    updateAddress(userName: any, addressDTO: any): Promise<string>;
    updatePhoneNumber(userName: any, phoneNumberDTO: any): Promise<string>;
    updateEmail(userName: any, alternetEmailDTO: any): Promise<string>;
    activate(email: any): Promise<any>;
    deactivate(email: any): Promise<any>;
    updateActivation(email: any, activation: any): Promise<any>;
    toggleActivation(email: any): Promise<any>;
    updateMaritalStatus(email: any): Promise<string>;
    deleteUser(email: any): Promise<any>;
    isActive(email: any): Promise<any>;
    isLocked(email: any): Promise<any>;
    lock(email: any): Promise<any>;
    unlock(email: any): Promise<any>;
    getAuthStatus(email: any): Promise<any>;
    addActivity(email: any, activityDTO: any): Promise<any>;
    getActivities(email: any): Promise<any>;
    isOnline(email: any): Promise<boolean>;
    getStatus(email: any): Promise<any>;
    changePassword(userName: any): Promise<string>;
    setPassword(email: any, newPassword: any): Promise<boolean>;
    getUsers(): Promise<any[]>;
    addUser(userDto: any): Promise<any>;
    updatePhoto(name: any, resp: any): Promise<any>;
    updateRoles(name: any, resp: any): Promise<any>;
    changeUserActivation(name: any, resp: any): Promise<any>;
    getUserPhoto(email: any): Promise<any>;
    getAccessRoutes(email: any): Promise<any[]>;
}
